FROM node:20.11.1-alpine

WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force
RUN npm install -g @nestjs/cli
RUN npm install --legacy-peer-deps

COPY . .

RUN npx prisma generate

RUN npm run build
COPY . .


EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]